cache:
  key: wp-otp
  paths:
  - vendor/

before_script:
- apk -U add icu-dev git
- curl -sS https://getcomposer.org/installer | php
- docker-php-ext-configure intl && docker-php-ext-install intl
- php composer.phar install

test:7.4:
  image: php:7.4-cli-alpine
  script: php composer.phar check-code
  tags: [dind]

test:8.0:
  image: php:8.0-cli-alpine
  script: php composer.phar check-code
  tags: [dind]
