build:
  environment:
    php: 7.4.0
  nodes:
    analysis:
      dependencies:
        before:
          - composer require --dev johnpbloch/wordpress
      tests:
        override:
          - php-scrutinizer-run

filter:
  excluded_paths:
    - vendor/

  dependency_paths:
    - wordpress/
